global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "blaybus-backend"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["web-server:8080"]
