spring:
  application:
    name: backend
  profiles:
    active: dev
    include: secret

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
