spring:
  application:
    name: backend
  profiles:
    active: dev
server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
